apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host:  k8schallengevmora.com
    http:
      paths:
      - path: /app1
        pathType: Prefix
        backend:
          service:
            name: app1
            port:
              number: 5000
      - path: /app2
        pathType: Prefix
        backend:
          service:
            name: app2
            port:
              number: 5000